version: 2
jobs:
  test_python:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd python
            python3 setup.py test
workflows:
  version: 2
  workflow:
    jobs:
    - test_python
