[package]
name = "aoc"
version = "0.2.0"
authors = ["mchlrhw <4028654+mchlrhw@users.noreply.github.com>"]
edition = "2018"

[dependencies]
fehler = "1.0.0-alpha"
thiserror = "1.0"

[dev-dependencies]
rstest = "0.4"
